# Generated by Django 5.2.1 on 2025-05-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_userprofile_batch_userprofile_p_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='p_members',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='batch',
            field=models.CharField(blank=True, choices=[('10A', '10A'), ('10B', '10B'), ('10C', '10C'), ('10D', '10D')], max_length=20, null=True),
        ),
    ]
