# Generated by Django 5.2.1 on 2025-05-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_remove_userprofile_p_members_alter_userprofile_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='n_adult',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='n_child',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='batch',
            field=models.CharField(choices=[('10A', '10A'), ('10B', '10B'), ('10C', '10C'), ('10D', '10D')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
