# Generated by Django 5.2.1 on 2025-05-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_userprofile_n_adult_userprofile_n_child_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('batch', models.CharField(choices=[('10A', '10A'), ('10B', '10B'), ('10C', '10C'), ('10D', '10D')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
            ],
        ),
    ]
