# Generated by Django 5.2.1 on 2025-05-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_teacherprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='batch',
            field=models.CharField(blank=True, choices=[('10A', '10A'), ('10B', '10B'), ('10C', '10C'), ('10D', '10D'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='phone',
            field=models.CharField(default='+91', max_length=15),
        ),
    ]
