# Generated by Django 5.2.1 on 2025-05-20 17:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo', models.ImageField(upload_to='event_photos/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.events')),
            ],
        ),
    ]
