# Generated by Django 5.2.1 on 2025-05-21 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_eventphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('video', models.FileField(upload_to='event_videos/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.events')),
            ],
        ),
    ]
