# Generated by Django 5.2.1 on 2025-05-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_eventvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='+91', max_length=15, unique=True),
        ),
    ]
