# Generated by Django 5.2.1 on 2025-05-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='subject',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
